const fields=[
 {id:'ai',name:'Artificial Intelligence',cat:'Intelligence',icon:'fa-brain',color:'#4378ff',desc:'Systems that learn, reason, and help us make better decisions.',apps:['AI tutors','Language tools','Predictive systems'],benefits:'Personalization, automation, and deeper insight.'},
 {id:'edtech',name:'Educational Technology',cat:'Education',icon:'fa-graduation-cap',color:'#8d6bff',desc:'Digital tools and platforms designed to make learning more accessible.',apps:['LMS platforms','Virtual classrooms','Digital assessment'],benefits:'Access, engagement, and collaboration.'},
 {id:'vr',name:'Virtual Reality',cat:'Immersive',icon:'fa-vr-cardboard',color:'#c35cff',desc:'Fully digital environments that make learning experiential.',apps:['Virtual labs','Simulations','3D tours'],benefits:'Safe practice and memorable learning.'},
 {id:'ar',name:'Augmented Reality',cat:'Immersive',icon:'fa-cube',color:'#ef6ea8',desc:'Digital layers that bring context and interaction to the physical world.',apps:['AR anatomy','Field guides','Interactive manuals'],benefits:'Contextual understanding and retention.'},
 {id:'xr',name:'Extended Reality',cat:'Immersive',icon:'fa-rocket',color:'#a758ff',desc:'The connected spectrum of AR, VR, and mixed reality.',apps:['XR classrooms','Remote collaboration','Training'],benefits:'Presence, creativity, and practice.'},
 {id:'iot',name:'Internet of Things',cat:'Connectivity',icon:'fa-wifi',color:'#11bfae',desc:'Connected devices that sense, share, and act on information.',apps:['Smart campuses','Sensors','Wearables'],benefits:'Automation and real-time awareness.'},
 {id:'cyber',name:'Cybersecurity',cat:'Security',icon:'fa-shield-halved',color:'#f06b71',desc:'Protecting people, systems, and data in an increasingly connected world.',apps:['Identity','Threat detection','Network defense'],benefits:'Trust, resilience, and safety.'},
 {id:'cloud',name:'Cloud Computing',cat:'Infrastructure',icon:'fa-cloud',color:'#3da9ff',desc:'On-demand computing power and services delivered over the internet.',apps:['Storage','Virtual labs','Collaboration'],benefits:'Scale, access, and flexibility.'},
 {id:'data',name:'Big Data',cat:'Data',icon:'fa-chart-line',color:'#efad3d',desc:'Finding meaningful patterns inside enormous, complex datasets.',apps:['Dashboards','Research','Forecasting'],benefits:'Evidence-based decisions.'},
 {id:'robotics',name:'Robotics',cat:'Automation',icon:'fa-robot',color:'#ec7661',desc:'Machines that sense, move, and assist humans in the real world.',apps:['STEM kits','Healthcare','Manufacturing'],benefits:'Precision, safety, and creativity.'},
 {id:'blockchain',name:'Blockchain',cat:'Security',icon:'fa-link',color:'#5d8aff',desc:'A transparent and tamper-resistant way to record digital events.',apps:['Credentials','Smart contracts','Identity'],benefits:'Trust and verifiability.'},
 {id:'ml',name:'Machine Learning',cat:'Intelligence',icon:'fa-diagram-project',color:'#795ff2',desc:'Algorithms that improve by recognizing patterns in data.',apps:['Recommendations','Recognition','Prediction'],benefits:'Scalable intelligence.'},
 {id:'digital',name:'Digital Learning',cat:'Education',icon:'fa-laptop-code',color:'#16bcae',desc:'Learning experiences delivered through connected digital tools.',apps:['E-learning','Hybrid courses','Video lessons'],benefits:'Flexibility and inclusion.'},
 {id:'analytics',name:'Learning Analytics',cat:'Education',icon:'fa-chart-simple',color:'#f19c45',desc:'Using learning data to improve support, teaching, and outcomes.',apps:['Progress tracking','Early alerts','Course insight'],benefits:'Better decisions for learners.'},
 {id:'meta',name:'Metaverse',cat:'Immersive',icon:'fa-cubes',color:'#ce68ed',desc:'Shared 3D spaces for social, creative, and educational experiences.',apps:['Virtual campuses','3D labs','Avatars'],benefits:'Presence and collaboration.'}
];
const education=[['fa-brain','AI-powered learning','Personalized content, pacing, and feedback for every learner.','#4378ff'],['fa-route','Adaptive learning','Flexible pathways that respond to strengths and challenges.','#8d6bff'],['fa-chalkboard-user','Virtual classrooms','Connected spaces for teachers, peers, and projects.','#15b9ab'],['fa-user-graduate','Intelligent tutoring','Real-time hints and guidance when it matters most.','#efad3d'],['fa-vr-cardboard','VR / AR learning','Explore difficult ideas through safe, immersive practice.','#e86aa5'],['fa-chart-pie','Learning analytics','Evidence that helps educators spot opportunities to support.','#f16f6f'],['fa-gamepad','Gamification','Quests, progress, and rewards that make persistence visible.','#5d8aff'],['fa-file-circle-check','Digital assessment','Faster feedback with richer evidence of understanding.','#c35cff']];
const timeline=[['1950s','fa-brain','The first spark','Foundations of machine intelligence begin.'],['1970s','fa-desktop','Computers enter classrooms','Early teaching systems make learning programmable.'],['1990s','fa-globe','The web opens up','Digital resources and online learning connect the world.'],['2000s','fa-cloud','Everything scales','Cloud services and mobile learning make access flexible.'],['2010s','fa-vr-cardboard','The world becomes immersive','AI, AR, VR, and data reshape digital experiences.'],['2020s','fa-wand-magic-sparkles','Learning gets intelligent','Adaptive platforms and AI tutors move into the mainstream.'],['NEXT','fa-rocket','The next frontier','Human-centered technology expands what is possible.']];
const resources=[['fa-book-open-reader','Research library','Build context with ideas from researchers and practitioners.','#4378ff'],['fa-code','Open-source tools','Explore the frameworks powering tomorrow’s intelligent systems.','#15b9ab'],['fa-globe','Learning communities','Find people, courses, and conversations to keep going.','#8d6bff'],['fa-toolbox','Try a new tool','Turn concepts into small experiments and real projects.','#efad3d']];
const qs=[['What is the main goal of AI in education?',['Replace teachers','Personalize learning','Remove assessment','Limit access'],1],['Which technology overlays digital content on the real world?',['VR','AR','Cloud','Blockchain'],1],['What does cybersecurity protect?',['Only devices','Digital systems and data','Printed books','Class schedules'],1],['Which field studies patterns in learner data?',['Robotics','Learning analytics','Metaverse','IoT'],1],['What is a major benefit of cloud computing?',['Scalable access','No networks','Less collaboration','Offline-only tools'],0]];
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
function renderFields(filter='All'){let list=filter==='All'?fields:fields.filter(x=>x.cat===filter);$('#fieldGrid').innerHTML=list.map(x=>`<article class="field-card reveal" style="--card-color:${x.color}"><div class="field-icon"><i class="fa-solid ${x.icon}"></i></div><span class="badge">${x.cat}</span><h3>${x.name}</h3><p>${x.desc}</p><span class="explore" data-id="${x.id}">Explore <i class="fa-solid fa-arrow-right"></i></span></article>`).join('');observe();$$('.explore').forEach(b=>b.onclick=()=>detail(fields.find(x=>x.id===b.dataset.id)))}
function renderFilters(){let cats=['All',...new Set(fields.map(x=>x.cat))];$('#filters').innerHTML=cats.map((x,i)=>`<button class="filter ${i?'':'active'}">${x}</button>`).join('');$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderFields(b.textContent)})}
function renderMap(){let positions=[[50,50],[23,25],[76,25],[21,73],[78,73],[50,17],[50,84],[9,49],[91,49]];let nodes=fields.slice(0,9);$('#mapCanvas').innerHTML=nodes.map((x,i)=>`<button class="map-node" data-id="${x.id}" style="left:${positions[i][0]}%;top:${positions[i][1]}%"><i class="fa-solid ${x.icon}"></i><span>${x.name.replace('Artificial Intelligence','AI').replace('Educational Technology','EdTech')}</span></button>`).join('');nodes.forEach((x,i)=>{let a=positions[0],b=positions[i];if(i)$('#mapCanvas').insertAdjacentHTML('afterbegin',`<i class="map-line" style="left:${a[0]}%;top:${a[1]}%;width:${Math.hypot(b[0]-a[0],b[1]-a[1])}%;transform:rotate(${Math.atan2(b[1]-a[1],b[0]-a[0])*180/Math.PI}deg)"></i>`)});$$('.map-node').forEach(n=>n.onclick=()=>{let x=fields.find(f=>f.id===n.dataset.id);$$('.map-node').forEach(y=>y.classList.remove('selected'));n.classList.add('selected');$('#mapInfo').innerHTML=`<span class="kicker">CONNECTED FIELD</span><div class="map-info-icon"><i class="fa-solid ${x.icon}"></i></div><h3>${x.name}</h3><p>${x.desc} Explore how it connects with ${x.apps.join(', ').toLowerCase()}.</p>`})}
function renderTimeline(){$('#timelineList').innerHTML=timeline.map(x=>`<article class="timeline-item"><div class="timeline-dot"><i class="fa-solid ${x[1]}"></i></div><div class="timeline-year">${x[0]}</div><h3>${x[2]}</h3><p>${x[3]}</p></article>`).join('')}
function renderEducation(){$('#educationGrid').innerHTML=education.map(x=>`<article class="edu-card" style="--edu-color:${x[3]}"><i class="fa-solid ${x[0]}"></i><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join('')}
function renderCompare(){let opts=fields.map(x=>`<option value="${x.id}">${x.name}</option>`).join('');$('#compareA').innerHTML=opts;$('#compareB').innerHTML=opts;$('#compareA').value='ai';$('#compareB').value='edtech';function go(){let a=fields.find(x=>x.id==$('#compareA').value),b=fields.find(x=>x.id==$('#compareB').value);$('#comparison').innerHTML=[a,b].map(x=>`<div class="compare-card"><span class="tag">${x.cat}</span><h3><i class="fa-solid ${x.icon}" style="color:${x.color}"></i> ${x.name}</h3><p>${x.desc}</p><ul><li><b>Applications:</b> ${x.apps.join(', ')}</li><li><b>Strength:</b> ${x.benefits}</li><li><b>Educational use:</b> Supports engaging, accessible learning experiences.</li></ul></div>`).join('')}$('#compareA').onchange=go;$('#compareB').onchange=go;go()}
function renderResources(){$('#resourcesGrid').innerHTML=resources.map(x=>`<article class="resource" style="--resource-color:${x[3]}"><i class="fa-solid ${x[0]}"></i><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join('')}
let qi=0,score=0;function renderQuiz(){let q=qs[qi];$('#quizApp').innerHTML=`<div class="quiz-top"><span>QUESTION ${qi+1} / ${qs.length}</span><span>${Math.round(qi/qs.length*100)}% COMPLETE</span></div><div class="progress"><i style="width:${qi/qs.length*100}%"></i></div><div class="quiz-question">${q[0]}</div><div class="answers">${q[1].map((x,i)=>`<button class="answer" data-i="${i}">${x}</button>`).join('')}</div>`;$$('.answer').forEach(b=>b.onclick=()=>{let buttons=$$('.answer');buttons.forEach(x=>x.disabled=true);if(+b.dataset.i===q[2]){b.classList.add('correct');score++}else{b.classList.add('wrong');buttons[q[2]].classList.add('correct')}setTimeout(()=>{qi++;qi<qs.length?renderQuiz():quizResult()},650)})}function quizResult(){$('#quizApp').innerHTML=`<div class="result"><div class="kicker">COMPLETE</div><strong>${score}/${qs.length}</strong><p>You’re building a strong foundation. Keep exploring to make it future-ready.</p><button class="button primary quiz-next" id="restart">Try again <i class="fa-solid fa-rotate-right"></i></button></div>`;$('#restart').onclick=()=>{qi=0;score=0;renderQuiz()}}
function detail(x){$('#detailContent').innerHTML=`<div class="kicker">${x.cat}</div><h2>${x.name}</h2><p>${x.desc}</p><div class="detail-grid"><div><h3>Applications</h3><ul>${x.apps.map(a=>`<li>${a}</li>`).join('')}</ul></div><div><h3>Why it matters</h3><p>${x.benefits}</p><h3>In education</h3><p>It helps create more active, inclusive, and meaningful learning experiences.</p></div></div>`;$('#detailModal').classList.remove('hidden')}
function observe(){let io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});$$('.reveal').forEach(e=>io.observe(e))}function counters(){let io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting&&!e.target.dataset.done){e.target.dataset.done=1;let n=+e.target.dataset.count,start=0;let t=setInterval(()=>{e.target.textContent=++start;if(start>=n)clearInterval(t)},35)}}),{threshold:.6});$$('[data-count]').forEach(e=>io.observe(e))}
renderFilters();renderFields();renderMap();renderTimeline();renderEducation();renderCompare();renderResources();renderQuiz();observe();counters();
$('#theme').onclick=()=>{document.body.classList.toggle('dark');localStorage.theme=document.body.classList.contains('dark')?'dark':'light'};if(localStorage.theme==='dark')document.body.classList.add('dark');
$('.menu-toggle').onclick=()=>$('.nav-links').classList.toggle('open');$$('.nav-links a').forEach(a=>a.onclick=()=>$('.nav-links').classList.remove('open'));
$('#searchOpen').onclick=()=>$('#searchModal').classList.remove('hidden');$('.close-overlay').onclick=()=>$('#searchModal').classList.add('hidden');$('.close-detail').onclick=()=>$('#detailModal').classList.add('hidden');$$('.overlay').forEach(o=>o.onclick=e=>{if(e.target===o)o.classList.add('hidden')});$('#searchInput').oninput=e=>{let q=e.target.value.toLowerCase();$('#searchResults').innerHTML=fields.filter(x=>(x.name+x.desc+x.cat).toLowerCase().includes(q)).slice(0,6).map(x=>`<div class="search-result" data-id="${x.id}"><b>${x.name}</b><small>${x.cat} · ${x.desc}</small></div>`).join('');$$('.search-result').forEach(r=>r.onclick=()=>{$('#searchModal').classList.add('hidden');detail(fields.find(x=>x.id===r.dataset.id))})};window.onscroll=()=>$('#top').classList.toggle('show',scrollY>600);$('#top').onclick=()=>scrollTo({top:0,behavior:'smooth'});
